### PR TITLE
Exception improvements

### PR DESCRIPTION
**Pull request by Flamefire**
- `detail::make_exception` renamed to `concat_args` to reflect what it does (and used better implementation)
- `make_exception` returns an exception now (reflects the name and makes it easier to reason about)
- `check` now includes a description int the error message

### CODE REVIEW

**Comment by Flamefire** [comment]
Why did you just use a small subset of this? What was wrong with this PR?

The commit you did now has multiple issues:

- `detail::make_exception` does not do what it is named for
- `detail::make_exception is wrong in terms of perfect forwarding: you are using rvalue references only but still call forward on it. I'd have to check it further but I think there are copies being made (probably eliminated through inlining though)
- `make_exception` does more than its name says: It throws. That hides this important information. E.g. it shouldn't be used in destructors as that would terminate the whole program.
- c6329f20112cc1aa58f4387ff74c347c8abd11e1 is ignored which means that there may be an extra copy for e.g. `throw otf2::exception("Foobar")`

**Comment by tilsche** [comment]
There is existing code which relies on the current behavior and naming.

**Comment by bmario** [comment]
> detail::make_exception does not do what it is named for

And I don't save princesses either

> `detail::make_exception is wrong in terms of perfect forwarding: you are using rvalue references only but still call forward on it. I'd have to check it further but I think there are copies being made (probably eliminated through inlining though)

the templates make them universal reference (as originally named by Scott Meyers) or forwarding references (which I believe they are called now)

> c6329f2 is ignored which means that there may be an extra copy for e.g. throw otf2::exception("Foobar")
Doing Copy& move for strings is definitely not the right thing to do.

**Comment by Flamefire** [comment]
> And I don't save princesses either

Good to know. Can we talk about code now?

> the templates make them universal reference (as originally named by Scott Meyers) or forwarding references (which I believe they are called now)

[Not the template as used ATM](https://github.com/tud-zih-energy/otf2xx/blob/f1f64cf959736db59c1caee0854d898133ae9af8/include/otf2xx/exception.hpp#L61) [Mine does.](https://github.com/tud-zih-energy/otf2xx/pull/21/commits/c7f1b266a5495d5d2ecbdb17878506d5780518da#diff-04fdb8b5ab7d58c5dbce8b1a62c5647eR58) It also renames only a detail type (no interface breaking change) and replaces >20 lines of code with more correct 8 lines.

> Doing Copy& move for strings is definitely not the right thing to do.

And this is based on what? My commit is based on e.g. https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html

**Comment by Flamefire** [comment]
> There is existing code which relies on the current behavior and naming.

Alternative: Rename to `create_exception` and provide a `make_exception` documented as deprecated that throws. So at least the library code is good.

**Comment by bmario** [comment]
> Not the template as used ATM Mine does.
I don't see your point, in particular because operator<< usually take their parameters by const-ref. 

> And this is based on what?
Herb Sutter's [talk at CppCon](https://stackoverflow.com/questions/26261007/why-is-value-taking-setter-member-functions-not-recommended-in-herb-sutters-cpp).

**Comment by Flamefire** [comment]
I was wondering why the code did work at all, which was a nice refresher to find out:

- Any rvalue passed will turn out as `Foo` in `Args`
- Any lvalue passed will turn out as `const Foo&` in `Args`
- Reference collapsing rules transform `const Foo& &&` into `const Foo&`

> I don't see your point, in particular because operator<< usually take their parameters by const-ref.

There are no universal references in the detail template, hence those forward calls are misleading. But they are working due to how the detail class is instantiated which was surprising to me. You could have just used const-refs.   
What was wrong with my 3 line, properly named function? It does what it says without all the clutter of the template declaration and specialization? (although the pre C++17 expansion is a bit weird, but still clear to understand)

>Herb Sutter's talk at CppCon.

You must have stopped reading before slide 32 and also before the end of the answer to the linked SO: `The above doesn't apply to constructors` (see also slides 32ff)

However it does not matter in practice for this because it seems libstdc++ `runtime_error` was not changed to take `std::string` by value.

**Pull request closed without merging**
